/* Auto-generated from include/vnd_sharkl3.txt on Sun Apr 24 15:58:07 CST 2022 */
#ifndef _VND_SHARKL3_H
#define _VND_SHARKL3_H
#define SPRD_WCNBT_SHARKL3
#define BLUETOOTH_UART_DEVICE_PORT   "/dev/ttyBT0"
#define LPM_IDLE_TIMEOUT_MULTIPLE   5
#define BTVND_DBG   TRUE
#define BTHW_DBG   TRUE
#define VNDUSERIAL_DBG   TRUE
#define UPIO_DBG   TRUE
#define PROC_BTWRITE_TIMER_TIMEOUT_MS   8000
#define BT_WAKE_VIA_PROC   FALSE
#define BT_WAKE_VIA_PROC_NOTIFY_DEASSERT   TRUE
#define BYTE_ALIGNMENT   0
#define BT_SITM_SERVICE   FALSE
#define BT_WCND_POWER_CTRL   FALSE
#define BT_RFKILL_CTRL   TRUE
#endif
