/******************************************************************************
 * This program is protected under international and U.S. copyright laws as
 * an unpublished work. This program is confidential and proprietary to the
 * copyright owners. Reproduction or disclosure, in whole or in part, or the
 * production of derivative works therefrom without the express permission of
 * the copyright owners is prohibited.
 *
 *                Copyright (C) 2018-2023 by Dolby International AB.
 *                            All rights reserved.
 ******************************************************************************
 *
 * THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT!
 *
 ******************************************************************************/
#ifndef   GENERATED_HEADER_DOLBYAC4BINDINGBLOB_IMPL_H_
#define   GENERATED_HEADER_DOLBYAC4BINDINGBLOB_IMPL_H_

#ifdef __cplusplus
extern "C" {
#endif

unsigned char dd_data[] = {
    0xf9, 0x07, 0xc1, 0x02, 0xa8, 0xec, 0x63, 0x30,
    0xf0, 0xd6, 0xc4, 0xa0, 0xef, 0xce, 0xee, 0xae
    };

#ifdef __cplusplus
}
#endif

#endif // GENERATED_HEADER_DOLBYAC4BINDINGBLOB_IMPL_H_

